import {
  Branch,
  Department,
  Staff,
  Patient,
  VitalSign,
  Appointment,
  OPDVisit,
  Medicine,
  LabTest,
  LabOrder,
  Prescription,
  Invoice,
  AuditLog,
  Notification,
  SystemSettings
} from '../types';

export const initialBranches: Branch[] = [
  {
    id: 'branch-main',
    name: 'PulseCare Central Medical Center',
    code: 'PCM-01',
    address: 'Bole Medhanealem Ave, Addis Ababa',
    phone: '+251 11 661 2000',
    email: 'info@pulsecare.et',
    isMain: true,
    active: true,
  },
  {
    id: 'branch-north',
    name: 'PulseCare North Specialty Hospital',
    code: 'PCN-02',
    address: 'Piazza Medical District, Addis Ababa',
    phone: '+251 11 155 3000',
    email: 'north@pulsecare.et',
    isMain: false,
    active: true,
  },
  {
    id: 'branch-east',
    name: 'PulseCare Eastside Ambulatory Clinic',
    code: 'PCE-03',
    address: 'CMC Road, Addis Ababa',
    phone: '+251 11 645 4000',
    email: 'east@pulsecare.et',
    isMain: false,
    active: true,
  },
];

export const initialDepartments: Department[] = [
  { id: 'dep-opd', branchId: 'branch-main', name: 'Outpatient (OPD)', code: 'OPD', description: 'General outpatient consultations and walk-ins' },
  { id: 'dep-im', branchId: 'branch-main', name: 'Internal Medicine', code: 'IM', description: 'Adult diseases and complex chronic conditions' },
  { id: 'dep-cardio', branchId: 'branch-main', name: 'Cardiology', code: 'CARD', description: 'Cardiovascular assessment and care' },
  { id: 'dep-ped', branchId: 'branch-main', name: 'Pediatrics', code: 'PED', description: 'Infant and child healthcare' },
  { id: 'dep-lab', branchId: 'branch-main', name: 'Pathology & Laboratory', code: 'LAB', description: 'Clinical testing and diagnostic analysis' },
  { id: 'dep-pharm', branchId: 'branch-main', name: 'Hospital Pharmacy', code: 'PHARM', description: 'Medication management and dispensing' },
  { id: 'dep-emergency', branchId: 'branch-main', name: 'Emergency & Trauma', code: 'ER', description: '24/7 urgent medical response' },
];

export const initialStaff: Staff[] = [
  {
    id: 'staff-admin-1',
    userId: 'user-admin-1',
    name: 'Dr. Almaz Bekele',
    role: 'admin',
    title: 'MD, Chief Executive Officer',
    departmentId: 'dep-opd',
    departmentName: 'Hospital Administration',
    branchId: 'branch-main',
    email: 'almaz.b@pulsecare.et',
    phone: '+251 91 122 3344',
    licenseNumber: 'MD-ET-0428',
    avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-doc-1',
    userId: 'user-doc-1',
    name: 'Dr. Dawit Abebe',
    role: 'doctor',
    title: 'MD, Chief of Internal Medicine',
    departmentId: 'dep-im',
    departmentName: 'Internal Medicine',
    branchId: 'branch-main',
    email: 'dawit.a@pulsecare.et',
    phone: '+251 91 233 4455',
    licenseNumber: 'MD-ET-1029',
    avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-doc-2',
    userId: 'user-doc-2',
    name: 'Dr. Meron Haile',
    role: 'doctor',
    title: 'MD, Consultant Cardiologist',
    departmentId: 'dep-cardio',
    departmentName: 'Cardiology',
    branchId: 'branch-main',
    email: 'meron.h@pulsecare.et',
    phone: '+251 91 344 5566',
    licenseNumber: 'MD-ET-1845',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813585-885741639f75?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-doc-3',
    userId: 'user-doc-3',
    name: 'Dr. Elias Tsegaye',
    role: 'doctor',
    title: 'MD, General Practitioner & OPD Lead',
    departmentId: 'dep-opd',
    departmentName: 'Outpatient (OPD)',
    branchId: 'branch-main',
    email: 'elias.t@pulsecare.et',
    phone: '+251 91 455 6677',
    licenseNumber: 'MD-ET-2210',
    avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-nurse-1',
    userId: 'user-nurse-1',
    name: 'Sister Selamawit Desta',
    role: 'nurse',
    title: 'BSN, Senior Triage Nurse Lead',
    departmentId: 'dep-opd',
    departmentName: 'Nursing Station',
    branchId: 'branch-main',
    email: 'selamawit.d@pulsecare.et',
    phone: '+251 91 566 7788',
    licenseNumber: 'RN-ET-5012',
    avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-nurse-2',
    userId: 'user-nurse-2',
    name: 'Nurse Robel Lemma',
    role: 'nurse',
    title: 'RN, Outpatient Vitals Specialist',
    departmentId: 'dep-opd',
    departmentName: 'Nursing Station',
    branchId: 'branch-main',
    email: 'robel.l@pulsecare.et',
    phone: '+251 91 677 8899',
    licenseNumber: 'RN-ET-5421',
    avatarUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-nurse-3',
    userId: 'user-nurse-3',
    name: 'Nurse Tigist Assefa',
    role: 'nurse',
    title: 'RN, Ward Nurse',
    departmentId: 'dep-im',
    departmentName: 'Inpatient Care',
    branchId: 'branch-main',
    email: 'tigist.a@pulsecare.et',
    phone: '+251 91 788 9900',
    licenseNumber: 'RN-ET-5890',
    avatarUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-nurse-4',
    userId: 'user-nurse-4',
    name: 'Nurse Bethlehem Kassa',
    role: 'nurse',
    title: 'RN, Emergency Care',
    departmentId: 'dep-emergency',
    departmentName: 'Emergency',
    branchId: 'branch-main',
    email: 'bethlehem.k@pulsecare.et',
    phone: '+251 91 899 0011',
    licenseNumber: 'RN-ET-6102',
    avatarUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-nurse-5',
    userId: 'user-nurse-5',
    name: 'Nurse Yonatan Girma',
    role: 'nurse',
    title: 'RN, Day Surgery Support',
    departmentId: 'dep-opd',
    departmentName: 'Nursing Station',
    branchId: 'branch-main',
    email: 'yonatan.g@pulsecare.et',
    phone: '+251 91 900 1122',
    licenseNumber: 'RN-ET-6344',
    avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-pharm-1',
    userId: 'user-pharm-1',
    name: 'PharmD Fitsum Tefera',
    role: 'pharmacist',
    title: 'PharmD, Chief Pharmacist',
    departmentId: 'dep-pharm',
    departmentName: 'Pharmacy',
    branchId: 'branch-main',
    email: 'fitsum.t@pulsecare.et',
    phone: '+251 91 011 2233',
    licenseNumber: 'PH-ET-2099',
    avatarUrl: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-pharm-2',
    userId: 'user-pharm-2',
    name: 'PharmD Rahel Mengistu',
    role: 'pharmacist',
    title: 'B.Pharm, Dispensing Pharmacist',
    departmentId: 'dep-pharm',
    departmentName: 'Pharmacy',
    branchId: 'branch-main',
    email: 'rahel.m@pulsecare.et',
    phone: '+251 91 123 3344',
    licenseNumber: 'PH-ET-2415',
    avatarUrl: 'https://images.unsplash.com/photo-1594824813585-885741639f75?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-lab-1',
    userId: 'user-lab-1',
    name: 'Yared Worku',
    role: 'lab_technician',
    title: 'MSc, Senior Clinical Biochemist',
    departmentId: 'dep-lab',
    departmentName: 'Laboratory',
    branchId: 'branch-main',
    email: 'yared.w@pulsecare.et',
    phone: '+251 91 234 4455',
    licenseNumber: 'LT-ET-1104',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-lab-2',
    userId: 'user-lab-2',
    name: 'Sara Tesfaye',
    role: 'lab_technician',
    title: 'BSc, Clinical Microbiologist',
    departmentId: 'dep-lab',
    departmentName: 'Laboratory',
    branchId: 'branch-main',
    email: 'sara.t@pulsecare.et',
    phone: '+251 91 345 5566',
    licenseNumber: 'LT-ET-1420',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-rec-1',
    userId: 'user-rec-1',
    name: 'Senait Kebede',
    role: 'receptionist',
    title: 'Senior Patient Registrar',
    departmentId: 'dep-opd',
    departmentName: 'Patient Access',
    branchId: 'branch-main',
    email: 'senait.k@pulsecare.et',
    phone: '+251 91 456 6677',
    licenseNumber: 'ADM-019',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-rec-2',
    userId: 'user-rec-2',
    name: 'Abel Mulugeta',
    role: 'receptionist',
    title: 'Front Desk Coordinator',
    departmentId: 'dep-opd',
    departmentName: 'Patient Access',
    branchId: 'branch-main',
    email: 'abel.m@pulsecare.et',
    phone: '+251 91 567 7788',
    licenseNumber: 'ADM-024',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-acc-1',
    userId: 'user-acc-1',
    name: 'Hanna Gizaw',
    role: 'accountant',
    title: 'BA, Senior Billing Officer',
    departmentId: 'dep-opd',
    departmentName: 'Finance & Billing',
    branchId: 'branch-main',
    email: 'hanna.g@pulsecare.et',
    phone: '+251 91 678 8899',
    licenseNumber: 'FIN-008',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
  {
    id: 'staff-acc-2',
    userId: 'user-acc-2',
    name: 'Tariku Fikru',
    role: 'accountant',
    title: 'Cashier & Insurance Specialist',
    departmentId: 'dep-opd',
    departmentName: 'Finance & Billing',
    branchId: 'branch-main',
    email: 'tariku.f@pulsecare.et',
    phone: '+251 91 789 9900',
    licenseNumber: 'FIN-015',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
  },
];

// Generate 52 Realistic Patients
const firstNames = ['Abebe', 'Almaz', 'Chala', 'Derartu', 'Eskinder', 'Fatuma', 'Girma', 'Hiwot', 'Kassahun', 'Lensa', 'Meseret', 'Natnael', 'Rahel', 'Solomon', 'Tigist', 'Yared', 'Zenebech', 'Bekele', 'Birtukan', 'Dawit', 'Ephrem', 'Frehiwot', 'Genet', 'Hana', 'Ismael', 'Jalene', 'Kidus', 'Lidia', 'Mahlet', 'Nebil', 'Obang', 'Ruth', 'Samrawit', 'Tewodros', 'Urji', 'Wondwossen', 'Yohannes', 'Zewdu', 'Alem', 'Bethlehem', 'Daniel', 'Emnet', 'Fasika', 'Getachew', 'Helen', 'Kalkidan', 'Mulugeta', 'Nardos', 'Robel', 'Saron', 'Tolera', 'Weynshet'];
const lastNames = ['Bekele', 'Tadesse', 'Alemu', 'Kebede', 'Girma', 'Haile', 'Mulugeta', 'Abebe', 'Desta', 'Tesfaye', 'Assefa', 'Worku', 'Fikru', 'Tsegaye', 'Kassa', 'Lemma', 'Mekonnen', 'Woldemariam', 'Mengistu', 'Ayalew', 'Gizaw', 'Gebre', 'Beshir', 'Tolosa', 'Kumsa', 'Dabala'];
const bloodGroups: Patient['bloodGroup'][] = ['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-'];
const allergiesList = ['Penicillin', 'Sulfa Drugs', 'Aspirin', 'NSAIDs', 'Latex', 'Codeine', 'Peanuts'];
const chronicList = ['Hypertension', 'Type 2 Diabetes', 'Asthma', 'Hyperlipidemia', 'Osteoarthritis', 'Migraine', 'Acid Reflux (GERD)'];
const insuranceProviders = ['Ethiopian Health Insurance Agency', 'Nyala Insurance', 'Awash Insurance', 'United Insurance', 'Africa Insurance', 'Self Pay / None'];

export const initialPatients: Patient[] = Array.from({ length: 52 }, (_, i) => {
  const fName = firstNames[i % firstNames.length];
  const lName = lastNames[(i * 3 + 2) % lastNames.length];
  const age = 18 + (i * 7) % 65;
  const birthYear = 2026 - age;
  const isFemale = i % 2 === 0;
  const hasInsurance = i % 4 !== 0;
  const branch = i % 10 === 0 ? 'branch-north' : i % 15 === 0 ? 'branch-east' : 'branch-main';
  
  return {
    id: `patient-${i + 1}`,
    mrn: `PC-2026-${String(i + 1).padStart(4, '0')}`,
    firstName: fName,
    lastName: lName,
    dateOfBirth: `${birthYear}-${String((i % 12) + 1).padStart(2, '0')}-${String((i % 28) + 1).padStart(2, '0')}`,
    gender: isFemale ? 'female' : 'male',
    bloodGroup: bloodGroups[i % bloodGroups.length],
    phone: `+251 9${String(10000000 + i * 13731).slice(0, 8)}`,
    email: `${fName.toLowerCase()}.${lName.toLowerCase()}${i}@example.et`,
    address: `Woreda ${(i % 14) + 1}, House #${100 + i * 7}`,
    city: 'Addis Ababa',
    branchId: branch,
    emergencyContact: {
      name: `${firstNames[(i + 4) % firstNames.length]} ${lName}`,
      relationship: isFemale ? 'Spouse' : 'Brother',
      phone: `+251 9${String(20000000 + i * 14829).slice(0, 8)}`,
    },
    insurance: {
      provider: hasInsurance ? insuranceProviders[i % (insuranceProviders.length - 1)] : 'Self Pay / None',
      policyNumber: hasInsurance ? `POL-2026-${8000 + i * 23}` : '',
      coveragePercent: hasInsurance ? (i % 2 === 0 ? 80 : 100) : 0,
      expiryDate: hasInsurance ? '2027-01-31' : '',
      isInsured: hasInsurance,
    },
    allergies: i % 3 === 0 ? [allergiesList[i % allergiesList.length]] : i % 5 === 0 ? [allergiesList[0], allergiesList[2]] : [],
    chronicConditions: i % 2 === 0 ? [chronicList[i % chronicList.length]] : [],
    registeredAt: `2026-0${Math.max(1, (i % 9) + 1)}-${String(1 + (i % 25)).padStart(2, '0')}T08:30:00Z`,
    status: i === 3 ? 'inpatient' : 'active',
  };
});

export const initialMedicines: Medicine[] = [
  {
    id: 'med-1',
    code: 'MED-AMOX-500',
    name: 'Amoxicillin 500mg',
    genericName: 'Amoxicillin Trihydrate',
    category: 'Antibiotics',
    strength: '500mg',
    dosageForm: 'capsule',
    unitPrice: 18.5,
    currentStock: 1420,
    minimumStock: 300,
    reorderLevel: 500,
    location: 'Aisle A, Shelf 2',
    branchId: 'branch-main',
    batches: [
      { id: 'b1', batchNumber: 'AMX-2025-09', expiryDate: '2027-08-30', quantity: 900, costPrice: 12.0, supplierName: 'Cadila Pharma' },
      { id: 'b2', batchNumber: 'AMX-2026-02', expiryDate: '2028-02-15', quantity: 520, costPrice: 12.5, supplierName: 'Cadila Pharma' },
    ],
  },
  {
    id: 'med-2',
    code: 'MED-METF-850',
    name: 'Metformin 850mg',
    genericName: 'Metformin Hydrochloride',
    category: 'Antidiabetic',
    strength: '850mg',
    dosageForm: 'tablet',
    unitPrice: 14.0,
    currentStock: 85, // Low stock demo!
    minimumStock: 200,
    reorderLevel: 350,
    location: 'Aisle B, Shelf 1',
    branchId: 'branch-main',
    batches: [
      { id: 'b3', batchNumber: 'MET-2025-11', expiryDate: '2026-12-10', quantity: 85, costPrice: 8.5, supplierName: 'EPHARM' },
    ],
  },
  {
    id: 'med-3',
    code: 'MED-AMLO-5',
    name: 'Amlodipine 5mg',
    genericName: 'Amlodipine Besylate',
    category: 'Antihypertensive',
    strength: '5mg',
    dosageForm: 'tablet',
    unitPrice: 22.0,
    currentStock: 940,
    minimumStock: 250,
    reorderLevel: 400,
    location: 'Aisle B, Shelf 4',
    branchId: 'branch-main',
    batches: [
      { id: 'b4', batchNumber: 'AML-2025-08', expiryDate: '2027-11-20', quantity: 940, costPrice: 15.0, supplierName: 'Julphar Ethiopia' },
    ],
  },
  {
    id: 'med-4',
    code: 'MED-PARA-500',
    name: 'Paracetamol 500mg',
    genericName: 'Acetaminophen',
    category: 'Analgesics / Antipyretic',
    strength: '500mg',
    dosageForm: 'tablet',
    unitPrice: 6.5,
    currentStock: 3200,
    minimumStock: 800,
    reorderLevel: 1200,
    location: 'Aisle A, Shelf 1',
    branchId: 'branch-main',
    batches: [
      { id: 'b5', batchNumber: 'PAR-2026-01', expiryDate: '2028-06-30', quantity: 3200, costPrice: 3.5, supplierName: 'EPHARM' },
    ],
  },
  {
    id: 'med-5',
    code: 'MED-AZITH-500',
    name: 'Azithromycin 500mg',
    genericName: 'Azithromycin Dihydrate',
    category: 'Antibiotics',
    strength: '500mg',
    dosageForm: 'tablet',
    unitPrice: 45.0,
    currentStock: 34, // Low stock demo!
    minimumStock: 150,
    reorderLevel: 250,
    location: 'Aisle A, Shelf 3',
    branchId: 'branch-main',
    batches: [
      { id: 'b6', batchNumber: 'AZI-2025-10', expiryDate: '2026-10-15', quantity: 34, costPrice: 30.0, supplierName: 'Cipla Med' },
    ],
  },
  {
    id: 'med-6',
    code: 'MED-OMEP-20',
    name: 'Omeprazole 20mg',
    genericName: 'Omeprazole Magnesium',
    category: 'Gastrointestinal',
    strength: '20mg',
    dosageForm: 'capsule',
    unitPrice: 19.0,
    currentStock: 1250,
    minimumStock: 300,
    reorderLevel: 500,
    location: 'Aisle C, Shelf 2',
    branchId: 'branch-main',
    batches: [
      { id: 'b7', batchNumber: 'OME-2025-12', expiryDate: '2027-09-15', quantity: 1250, costPrice: 12.0, supplierName: 'Julphar Ethiopia' },
    ],
  },
  {
    id: 'med-7',
    code: 'MED-ATOR-20',
    name: 'Atorvastatin 20mg',
    genericName: 'Atorvastatin Calcium',
    category: 'Lipid Lowering',
    strength: '20mg',
    dosageForm: 'tablet',
    unitPrice: 38.0,
    currentStock: 480,
    minimumStock: 200,
    reorderLevel: 300,
    location: 'Aisle B, Shelf 3',
    branchId: 'branch-main',
    batches: [
      { id: 'b8', batchNumber: 'ATO-2025-07', expiryDate: '2027-05-18', quantity: 480, costPrice: 26.0, supplierName: 'Sun Pharma' },
    ],
  },
  {
    id: 'med-8',
    code: 'MED-SALB-INH',
    name: 'Salbutamol Inhaler 100mcg',
    genericName: 'Albuterol Sulfate',
    category: 'Respiratory',
    strength: '100mcg/dose',
    dosageForm: 'inhaler',
    unitPrice: 185.0,
    currentStock: 18, // Critical stock!
    minimumStock: 50,
    reorderLevel: 80,
    location: 'Aisle D, Shelf 1',
    branchId: 'branch-main',
    batches: [
      { id: 'b9', batchNumber: 'SLB-2025-06', expiryDate: '2026-11-30', quantity: 18, costPrice: 135.0, supplierName: 'GSK Global' },
    ],
  },
  {
    id: 'med-9',
    code: 'MED-CEFT-1G',
    name: 'Ceftriaxone 1g Injection',
    genericName: 'Ceftriaxone Sodium',
    category: 'Injectable Antibiotics',
    strength: '1g vial',
    dosageForm: 'injection',
    unitPrice: 120.0,
    currentStock: 320,
    minimumStock: 100,
    reorderLevel: 200,
    location: 'Fridge A, Shelf 2',
    branchId: 'branch-main',
    batches: [
      { id: 'b10', batchNumber: 'CFT-2026-03', expiryDate: '2028-01-20', quantity: 320, costPrice: 85.0, supplierName: 'Sandoz' },
    ],
  },
];

export const initialLabTests: LabTest[] = [
  {
    id: 'lab-cbc',
    code: 'LAB-001',
    name: 'Complete Blood Count (CBC) with Diff',
    category: 'Hematology',
    sampleType: 'Blood',
    price: 350,
    turnaroundHours: 2,
    referenceRanges: [
      { parameter: 'Hemoglobin (Hgb)', normalMin: 12.0, normalMax: 16.5, unit: 'g/dL' },
      { parameter: 'White Blood Cells (WBC)', normalMin: 4.5, normalMax: 11.0, unit: 'x10^3/uL' },
      { parameter: 'Platelets (PLT)', normalMin: 150, normalMax: 450, unit: 'x10^3/uL' },
      { parameter: 'Hematocrit (Hct)', normalMin: 36.0, normalMax: 48.0, unit: '%' },
    ],
  },
  {
    id: 'lab-cmp',
    code: 'LAB-002',
    name: 'Comprehensive Metabolic Panel (CMP)',
    category: 'Biochemistry',
    sampleType: 'Serum',
    price: 680,
    turnaroundHours: 3,
    referenceRanges: [
      { parameter: 'Fasting Blood Glucose', normalMin: 70, normalMax: 99, unit: 'mg/dL' },
      { parameter: 'Serum Creatinine', normalMin: 0.6, normalMax: 1.2, unit: 'mg/dL' },
      { parameter: 'Blood Urea Nitrogen (BUN)', normalMin: 7, normalMax: 20, unit: 'mg/dL' },
      { parameter: 'Serum Potassium (K+)', normalMin: 3.5, normalMax: 5.1, unit: 'mmol/L' },
      { parameter: 'Serum Sodium (Na+)', normalMin: 135, normalMax: 145, unit: 'mmol/L' },
      { parameter: 'ALT (Alanine Aminotransferase)', normalMin: 7, normalMax: 56, unit: 'U/L' },
    ],
  },
  {
    id: 'lab-lipid',
    code: 'LAB-003',
    name: 'Lipid Profile Panel',
    category: 'Biochemistry',
    sampleType: 'Serum',
    price: 520,
    turnaroundHours: 3,
    referenceRanges: [
      { parameter: 'Total Cholesterol', normalMin: 120, normalMax: 200, unit: 'mg/dL' },
      { parameter: 'HDL (Good) Cholesterol', normalMin: 40, normalMax: 60, unit: 'mg/dL' },
      { parameter: 'LDL (Bad) Cholesterol', normalMin: 0, normalMax: 100, unit: 'mg/dL' },
      { parameter: 'Triglycerides', normalMin: 50, normalMax: 150, unit: 'mg/dL' },
    ],
  },
  {
    id: 'lab-hba1c',
    code: 'LAB-004',
    name: 'Glycated Hemoglobin (HbA1c)',
    category: 'Biochemistry',
    sampleType: 'Blood',
    price: 480,
    turnaroundHours: 2,
    referenceRanges: [
      { parameter: 'HbA1c', normalMin: 4.0, normalMax: 5.6, unit: '%' },
    ],
  },
  {
    id: 'lab-malaria',
    code: 'LAB-005',
    name: 'Malaria Rapid & Blood Film Exam',
    category: 'Microbiology',
    sampleType: 'Blood',
    price: 220,
    turnaroundHours: 1,
    referenceRanges: [
      { parameter: 'Plasmodium Falciparum / Vivax', normalMin: 0, normalMax: 0, unit: 'presence' },
    ],
  },
  {
    id: 'lab-urine',
    code: 'LAB-006',
    name: 'Routine Urinalysis with Microscopy',
    category: 'Pathology',
    sampleType: 'Urine',
    price: 180,
    turnaroundHours: 1,
    referenceRanges: [
      { parameter: 'Urine Protein', normalMin: 0, normalMax: 0, unit: 'mg/dL' },
      { parameter: 'Urine Glucose', normalMin: 0, normalMax: 0, unit: 'mg/dL' },
      { parameter: 'WBC per HPF', normalMin: 0, normalMax: 4, unit: '/hpf' },
    ],
  },
];

export const initialVitalSigns: VitalSign[] = [
  // Patient 1 (Abebe Bekele) - Longitudinal BP & HR follow-up
  {
    id: 'vit-1-1',
    patientId: 'patient-1',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-08-12T09:00:00Z',
    bloodPressureSystolic: 138,
    bloodPressureDiastolic: 88,
    heartRate: 82,
    temperature: 36.6,
    respiratoryRate: 16,
    spO2: 98,
    weightKg: 74.0,
    heightCm: 175,
    bmi: 24.2,
    notes: 'Initial follow-up. Mild borderline hypertension noted.',
    status: 'warning',
  },
  {
    id: 'vit-1-2',
    patientId: 'patient-1',
    recordedBy: 'staff-nurse-2',
    recordedByName: 'Nurse Robel Lemma',
    recordedAt: '2026-08-26T10:15:00Z',
    bloodPressureSystolic: 134,
    bloodPressureDiastolic: 86,
    heartRate: 78,
    temperature: 36.7,
    respiratoryRate: 16,
    spO2: 98,
    weightKg: 73.5,
    heightCm: 175,
    bmi: 24.0,
    notes: 'Dietary sodium reduction advised. BP improving.',
    status: 'normal',
  },
  {
    id: 'vit-1-3',
    patientId: 'patient-1',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-09-09T08:45:00Z',
    bloodPressureSystolic: 130,
    bloodPressureDiastolic: 84,
    heartRate: 76,
    temperature: 36.7,
    respiratoryRate: 15,
    spO2: 99,
    weightKg: 73.0,
    heightCm: 175,
    bmi: 23.8,
    notes: 'Steady improvement with aerobic exercise routines.',
    status: 'normal',
  },
  {
    id: 'vit-1-4',
    patientId: 'patient-1',
    recordedBy: 'staff-nurse-3',
    recordedByName: 'Nurse Tigist Assefa',
    recordedAt: '2026-09-18T14:30:00Z',
    bloodPressureSystolic: 124,
    bloodPressureDiastolic: 80,
    heartRate: 72,
    temperature: 36.6,
    respiratoryRate: 16,
    spO2: 98,
    weightKg: 72.8,
    heightCm: 175,
    bmi: 23.8,
    notes: 'Good adherence to recommendations. Vitals optimal.',
    status: 'normal',
  },
  {
    id: 'vit-1-5',
    patientId: 'patient-1',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-09-25T08:15:00Z',
    bloodPressureSystolic: 128,
    bloodPressureDiastolic: 82,
    heartRate: 74,
    temperature: 36.8,
    respiratoryRate: 16,
    spO2: 98,
    weightKg: 72.5,
    heightCm: 175,
    bmi: 23.7,
    notes: 'Patient feels slightly fatigued, resting comfortably.',
    status: 'normal',
  },

  // Patient 2 (Almaz Tadesse) - Hypertensive chronic trajectory
  {
    id: 'vit-2-1',
    patientId: 'patient-2',
    recordedBy: 'staff-nurse-2',
    recordedByName: 'Nurse Robel Lemma',
    recordedAt: '2026-07-20T10:00:00Z',
    bloodPressureSystolic: 168,
    bloodPressureDiastolic: 104,
    heartRate: 94,
    temperature: 36.9,
    respiratoryRate: 18,
    spO2: 96,
    weightKg: 90.0,
    heightCm: 168,
    bmi: 31.9,
    notes: 'Stage 2 Hypertension crisis. Started on Amlodipine 5mg.',
    status: 'critical',
  },
  {
    id: 'vit-2-2',
    patientId: 'patient-2',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-08-05T09:30:00Z',
    bloodPressureSystolic: 158,
    bloodPressureDiastolic: 98,
    heartRate: 88,
    temperature: 36.8,
    respiratoryRate: 17,
    spO2: 97,
    weightKg: 89.2,
    heightCm: 168,
    bmi: 31.6,
    notes: 'Moderate response to antihypertensive medication.',
    status: 'warning',
  },
  {
    id: 'vit-2-3',
    patientId: 'patient-2',
    recordedBy: 'staff-nurse-2',
    recordedByName: 'Nurse Robel Lemma',
    recordedAt: '2026-08-25T11:00:00Z',
    bloodPressureSystolic: 146,
    bloodPressureDiastolic: 92,
    heartRate: 84,
    temperature: 36.7,
    respiratoryRate: 16,
    spO2: 97,
    weightKg: 88.5,
    heightCm: 168,
    bmi: 31.4,
    notes: 'Blood pressure trending down toward goal.',
    status: 'warning',
  },
  {
    id: 'vit-2-4',
    patientId: 'patient-2',
    recordedBy: 'staff-nurse-3',
    recordedByName: 'Nurse Tigist Assefa',
    recordedAt: '2026-09-12T10:45:00Z',
    bloodPressureSystolic: 140,
    bloodPressureDiastolic: 88,
    heartRate: 80,
    temperature: 36.8,
    respiratoryRate: 16,
    spO2: 98,
    weightKg: 88.0,
    heightCm: 168,
    bmi: 31.2,
    notes: 'Good control on combination regimen.',
    status: 'normal',
  },
  {
    id: 'vit-2-5',
    patientId: 'patient-2',
    recordedBy: 'staff-nurse-2',
    recordedByName: 'Nurse Robel Lemma',
    recordedAt: '2026-09-25T08:30:00Z',
    bloodPressureSystolic: 154,
    bloodPressureDiastolic: 96,
    heartRate: 88,
    temperature: 37.1,
    respiratoryRate: 18,
    spO2: 96,
    weightKg: 88.0,
    heightCm: 168,
    bmi: 31.2,
    notes: 'Hypertensive reading. Patient missed morning dose of Amlodipine.',
    status: 'warning',
  },

  // Patient 3 (Tigist Haile) - Febrile episode trajectory
  {
    id: 'vit-3-1',
    patientId: 'patient-3',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-09-22T08:00:00Z',
    bloodPressureSystolic: 120,
    bloodPressureDiastolic: 78,
    heartRate: 72,
    temperature: 36.6,
    respiratoryRate: 16,
    spO2: 99,
    weightKg: 64.2,
    heightCm: 162,
    bmi: 24.5,
    notes: 'Baseline pre-illness vitals.',
    status: 'normal',
  },
  {
    id: 'vit-3-2',
    patientId: 'patient-3',
    recordedBy: 'staff-nurse-2',
    recordedByName: 'Nurse Robel Lemma',
    recordedAt: '2026-09-23T14:20:00Z',
    bloodPressureSystolic: 122,
    bloodPressureDiastolic: 80,
    heartRate: 86,
    temperature: 37.4,
    respiratoryRate: 18,
    spO2: 98,
    weightKg: 64.0,
    heightCm: 162,
    bmi: 24.4,
    notes: 'Mild fever and dry cough onset.',
    status: 'normal',
  },
  {
    id: 'vit-3-3',
    patientId: 'patient-3',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-09-24T18:00:00Z',
    bloodPressureSystolic: 116,
    bloodPressureDiastolic: 74,
    heartRate: 98,
    temperature: 38.3,
    respiratoryRate: 20,
    spO2: 96,
    weightKg: 63.8,
    heightCm: 162,
    bmi: 24.3,
    notes: 'Moderate fever, heart rate elevated (sinus tachycardia due to fever).',
    status: 'warning',
  },
  {
    id: 'vit-3-4',
    patientId: 'patient-3',
    recordedBy: 'staff-nurse-1',
    recordedByName: 'Sister Selamawit Desta',
    recordedAt: '2026-09-25T09:00:00Z',
    bloodPressureSystolic: 118,
    bloodPressureDiastolic: 76,
    heartRate: 104,
    temperature: 38.6,
    respiratoryRate: 22,
    spO2: 95,
    weightKg: 64.0,
    heightCm: 162,
    bmi: 24.4,
    notes: 'Febrile episode, chills and malaise.',
    status: 'warning',
  },

  // Patient 4 (Dawit Yohannes) - Severe acute cardiovascular progression
  {
    id: 'vit-4-1',
    patientId: 'patient-4',
    recordedBy: 'staff-nurse-4',
    recordedByName: 'Nurse Bethlehem Kassa',
    recordedAt: '2026-08-20T10:00:00Z',
    bloodPressureSystolic: 148,
    bloodPressureDiastolic: 92,
    heartRate: 84,
    temperature: 36.8,
    respiratoryRate: 18,
    spO2: 96,
    weightKg: 96.0,
    heightCm: 178,
    bmi: 30.3,
    notes: 'Previous checkup, elevated baseline BP.',
    status: 'warning',
  },
  {
    id: 'vit-4-2',
    patientId: 'patient-4',
    recordedBy: 'staff-nurse-4',
    recordedByName: 'Nurse Bethlehem Kassa',
    recordedAt: '2026-09-05T11:30:00Z',
    bloodPressureSystolic: 160,
    bloodPressureDiastolic: 98,
    heartRate: 92,
    temperature: 36.9,
    respiratoryRate: 20,
    spO2: 95,
    weightKg: 95.5,
    heightCm: 178,
    bmi: 30.1,
    notes: 'Uncontrolled hypertension noted.',
    status: 'warning',
  },
  {
    id: 'vit-4-3',
    patientId: 'patient-4',
    recordedBy: 'staff-nurse-4',
    recordedByName: 'Nurse Bethlehem Kassa',
    recordedAt: '2026-09-18T16:00:00Z',
    bloodPressureSystolic: 172,
    bloodPressureDiastolic: 106,
    heartRate: 102,
    temperature: 37.0,
    respiratoryRate: 22,
    spO2: 94,
    weightKg: 95.2,
    heightCm: 178,
    bmi: 30.0,
    notes: 'Severe hypertension with mild exertional dyspnea.',
    status: 'critical',
  },
  {
    id: 'vit-4-4',
    patientId: 'patient-4',
    recordedBy: 'staff-nurse-4',
    recordedByName: 'Nurse Bethlehem Kassa',
    recordedAt: '2026-09-25T09:20:00Z',
    bloodPressureSystolic: 182,
    bloodPressureDiastolic: 112,
    heartRate: 112,
    temperature: 37.0,
    respiratoryRate: 24,
    spO2: 92,
    weightKg: 95.0,
    heightCm: 178,
    bmi: 30.0,
    notes: 'Severe chest tightness and dyspnea. Urgent medical alert flagged.',
    status: 'critical',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    patientId: 'patient-1',
    patientName: 'Abebe Bekele',
    patientMrn: 'PC-2026-0001',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    departmentId: 'dep-im',
    departmentName: 'Internal Medicine',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '09:00',
    durationMinutes: 30,
    reason: 'Follow-up for seasonal allergies & routine metabolic check',
    status: 'in_consultation',
    createdAt: '2026-09-24T14:20:00Z',
  },
  {
    id: 'apt-2',
    patientId: 'patient-2',
    patientName: 'Almaz Tadesse',
    patientMrn: 'PC-2026-0002',
    doctorId: 'staff-doc-2',
    doctorName: 'Dr. Meron Haile',
    departmentId: 'dep-cardio',
    departmentName: 'Cardiology',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '09:30',
    durationMinutes: 30,
    reason: 'Hypertension monitoring and medication adjustment',
    status: 'checked_in',
    createdAt: '2026-09-23T10:15:00Z',
  },
  {
    id: 'apt-3',
    patientId: 'patient-3',
    patientName: 'Chala Alemu',
    patientMrn: 'PC-2026-0003',
    doctorId: 'staff-doc-3',
    doctorName: 'Dr. Elias Tsegaye',
    departmentId: 'dep-opd',
    departmentName: 'Outpatient (OPD)',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '10:00',
    durationMinutes: 20,
    reason: 'Acute fever, headache and muscle ache since yesterday',
    status: 'checked_in',
    createdAt: '2026-09-25T07:45:00Z',
  },
  {
    id: 'apt-4',
    patientId: 'patient-4',
    patientName: 'Derartu Kebede',
    patientMrn: 'PC-2026-0004',
    doctorId: 'staff-doc-2',
    doctorName: 'Dr. Meron Haile',
    departmentId: 'dep-cardio',
    departmentName: 'Cardiology',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '10:30',
    durationMinutes: 45,
    reason: 'Exertional chest discomfort and palpitation',
    status: 'scheduled',
    createdAt: '2026-09-22T16:00:00Z',
  },
  {
    id: 'apt-5',
    patientId: 'patient-5',
    patientName: 'Eskinder Girma',
    patientMrn: 'PC-2026-0005',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    departmentId: 'dep-im',
    departmentName: 'Internal Medicine',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '11:15',
    durationMinutes: 30,
    reason: 'Type 2 Diabetes quarterly HbA1c review',
    status: 'scheduled',
    createdAt: '2026-09-21T11:30:00Z',
  },
  {
    id: 'apt-6',
    patientId: 'patient-6',
    patientName: 'Fatuma Haile',
    patientMrn: 'PC-2026-0006',
    doctorId: 'staff-doc-3',
    doctorName: 'Dr. Elias Tsegaye',
    departmentId: 'dep-opd',
    departmentName: 'Outpatient (OPD)',
    branchId: 'branch-main',
    date: '2026-09-25',
    time: '11:45',
    durationMinutes: 20,
    reason: 'Persistent epigastric burning sensation',
    status: 'scheduled',
    createdAt: '2026-09-25T08:10:00Z',
  },
];

export const initialOPDVisits: OPDVisit[] = [
  {
    id: 'visit-1',
    patientId: 'patient-1',
    patientName: 'Abebe Bekele',
    patientMrn: 'PC-2026-0001',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    branchId: 'branch-main',
    queueNumber: 'OPD-001',
    stage: 'consultation',
    priority: 'routine',
    arrivalTime: '2026-09-25T08:10:00Z',
    chiefComplaint: 'Mild rhinorrhea, throat tickle and fatigue for 3 days.',
    vitalsId: 'vit-1',
    diagnosis: 'Acute Viral Upper Respiratory Tract Infection (J06.9)',
    clinicalNotes: 'Clear lung sounds bilaterally. No purulent exudate on tonsils. Vitals stable.',
    treatmentPlan: 'Hydration, supportive rest, Paracetamol for discomfort.',
  },
  {
    id: 'visit-2',
    patientId: 'patient-2',
    patientName: 'Almaz Tadesse',
    patientMrn: 'PC-2026-0002',
    doctorId: 'staff-doc-2',
    doctorName: 'Dr. Meron Haile',
    branchId: 'branch-main',
    queueNumber: 'OPD-002',
    stage: 'doctor_queue',
    priority: 'routine',
    arrivalTime: '2026-09-25T08:25:00Z',
    chiefComplaint: 'Morning occipital headache, forgot anti-hypertensive pills yesterday.',
    vitalsId: 'vit-2',
  },
  {
    id: 'visit-3',
    patientId: 'patient-3',
    patientName: 'Chala Alemu',
    patientMrn: 'PC-2026-0003',
    doctorId: 'staff-doc-3',
    doctorName: 'Dr. Elias Tsegaye',
    branchId: 'branch-main',
    queueNumber: 'OPD-003',
    stage: 'lab_pharmacy',
    priority: 'urgent',
    arrivalTime: '2026-09-25T08:45:00Z',
    chiefComplaint: 'High grade fever with rigors, sweating, headache.',
    vitalsId: 'vit-3',
    diagnosis: 'Suspected Malaria / Acute Febrile Illness',
    treatmentPlan: 'Ordered Rapid Malaria Antigen & CBC. Pending results.',
  },
  {
    id: 'visit-4',
    patientId: 'patient-4',
    patientName: 'Derartu Kebede',
    patientMrn: 'PC-2026-0004',
    doctorId: 'staff-doc-2',
    doctorName: 'Dr. Meron Haile',
    branchId: 'branch-main',
    queueNumber: 'OPD-004',
    stage: 'triage',
    priority: 'emergency',
    arrivalTime: '2026-09-25T09:15:00Z',
    chiefComplaint: 'Acute chest pain radiating to left arm with diaphoresis.',
    vitalsId: 'vit-4',
  },
];

export const initialLabOrders: LabOrder[] = [
  {
    id: 'order-1',
    orderNumber: 'LAB-2026-0101',
    patientId: 'patient-3',
    patientName: 'Chala Alemu',
    patientMrn: 'PC-2026-0003',
    doctorId: 'staff-doc-3',
    doctorName: 'Dr. Elias Tsegaye',
    branchId: 'branch-main',
    tests: [
      { testId: 'lab-cbc', testName: 'Complete Blood Count (CBC)', price: 350 },
      { testId: 'lab-malaria', testName: 'Malaria Rapid & Blood Film Exam', price: 220 },
    ],
    status: 'in_progress',
    clinicalNotes: 'Evaluate fever, rule out malaria parasite or leukocytosis.',
    orderedAt: '2026-09-25T09:05:00Z',
    collectedAt: '2026-09-25T09:18:00Z',
    results: [
      { parameter: 'Hemoglobin (Hgb)', value: '14.2', numericValue: 14.2, unit: 'g/dL', referenceRange: '12.0 - 16.5', flag: 'normal' },
      { parameter: 'White Blood Cells (WBC)', value: '11.8', numericValue: 11.8, unit: 'x10^3/uL', referenceRange: '4.5 - 11.0', flag: 'high' },
      { parameter: 'Plasmodium Falciparum / Vivax', value: 'Positive (P. falciparum trophozoites seen)', unit: 'presence', referenceRange: 'Negative', flag: 'critical' },
    ],
    technicianNotes: 'Blood smear confirmed ring forms of P. falciparum (~1.2% parasitemia).',
  },
  {
    id: 'order-2',
    orderNumber: 'LAB-2026-0102',
    patientId: 'patient-5',
    patientName: 'Eskinder Girma',
    patientMrn: 'PC-2026-0005',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    branchId: 'branch-main',
    tests: [
      { testId: 'lab-hba1c', testName: 'Glycated Hemoglobin (HbA1c)', price: 480 },
      { testId: 'lab-cmp', testName: 'Comprehensive Metabolic Panel (CMP)', price: 680 },
    ],
    status: 'verified',
    clinicalNotes: 'Annual diabetic nephropathy & glycemic control workup.',
    orderedAt: '2026-09-24T14:30:00Z',
    collectedAt: '2026-09-24T15:00:00Z',
    completedAt: '2026-09-24T17:15:00Z',
    verifiedBy: 'Yared Worku (Senior Clinical Biochemist)',
    results: [
      { parameter: 'HbA1c', value: '7.4', numericValue: 7.4, unit: '%', referenceRange: '4.0 - 5.6', flag: 'high' },
      { parameter: 'Fasting Blood Glucose', value: '142', numericValue: 142, unit: 'mg/dL', referenceRange: '70 - 99', flag: 'high' },
      { parameter: 'Serum Creatinine', value: '0.9', numericValue: 0.9, unit: 'mg/dL', referenceRange: '0.6 - 1.2', flag: 'normal' },
      { parameter: 'Blood Urea Nitrogen (BUN)', value: '14', numericValue: 14, unit: 'mg/dL', referenceRange: '7 - 20', flag: 'normal' },
    ],
  },
  {
    id: 'order-3',
    orderNumber: 'LAB-2026-0103',
    patientId: 'patient-2',
    patientName: 'Almaz Tadesse',
    patientMrn: 'PC-2026-0002',
    doctorId: 'staff-doc-2',
    doctorName: 'Dr. Meron Haile',
    branchId: 'branch-main',
    tests: [
      { testId: 'lab-lipid', testName: 'Lipid Profile Panel', price: 520 },
      { testId: 'lab-cmp', testName: 'Comprehensive Metabolic Panel (CMP)', price: 680 },
    ],
    status: 'ordered',
    clinicalNotes: 'Check electrolytes and lipid fractions prior to medication titration.',
    orderedAt: '2026-09-25T08:35:00Z',
  },
];

export const initialPrescriptions: Prescription[] = [
  {
    id: 'rx-1',
    patientId: 'patient-1',
    patientName: 'Abebe Bekele',
    patientMrn: 'PC-2026-0001',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    branchId: 'branch-main',
    items: [
      {
        medicineId: 'med-4',
        medicineName: 'Paracetamol 500mg',
        dosage: '500mg',
        frequency: 'Every 8 hours as needed for headache',
        duration: '5 days',
        instructions: 'Take after meals with water',
        quantity: 15,
        dispensedQuantity: 15,
        unitPrice: 6.5,
      },
    ],
    status: 'dispensed',
    createdAt: '2026-09-25T08:45:00Z',
    dispensedAt: '2026-09-25T09:05:00Z',
    dispensedBy: 'PharmD Fitsum Tefera',
    notes: 'Counselled patient on max daily dosage of acetaminophen.',
  },
  {
    id: 'rx-2',
    patientId: 'patient-3',
    patientName: 'Chala Alemu',
    patientMrn: 'PC-2026-0003',
    doctorId: 'staff-doc-3',
    doctorName: 'Dr. Elias Tsegaye',
    branchId: 'branch-main',
    items: [
      {
        medicineId: 'med-1',
        medicineName: 'Amoxicillin 500mg',
        dosage: '500mg',
        frequency: 'Three times daily',
        duration: '7 days',
        instructions: 'Complete full course even if symptoms subside',
        quantity: 21,
        dispensedQuantity: 0,
        unitPrice: 18.5,
      },
      {
        medicineId: 'med-4',
        medicineName: 'Paracetamol 500mg',
        dosage: '500mg',
        frequency: 'Three times daily',
        duration: '3 days',
        instructions: 'Take for fever relief',
        quantity: 10,
        dispensedQuantity: 0,
        unitPrice: 6.5,
      },
    ],
    status: 'pending',
    createdAt: '2026-09-25T09:20:00Z',
    notes: 'Prescription ready for pharmacy dispensing.',
  },
  {
    id: 'rx-3',
    patientId: 'patient-5',
    patientName: 'Eskinder Girma',
    patientMrn: 'PC-2026-0005',
    doctorId: 'staff-doc-1',
    doctorName: 'Dr. Dawit Abebe',
    branchId: 'branch-main',
    items: [
      {
        medicineId: 'med-2',
        medicineName: 'Metformin 850mg',
        dosage: '850mg',
        frequency: 'Twice daily with meals',
        duration: '30 days',
        instructions: 'Morning and evening with meals to reduce GI irritation',
        quantity: 60,
        dispensedQuantity: 60,
        unitPrice: 14.0,
      },
      {
        medicineId: 'med-7',
        medicineName: 'Atorvastatin 20mg',
        dosage: '20mg',
        frequency: 'Once daily at bedtime',
        duration: '30 days',
        instructions: 'Take in the evening',
        quantity: 30,
        dispensedQuantity: 30,
        unitPrice: 38.0,
      },
    ],
    status: 'dispensed',
    createdAt: '2026-09-24T16:00:00Z',
    dispensedAt: '2026-09-24T16:25:00Z',
    dispensedBy: 'PharmD Rahel Mengistu',
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2026-0101',
    patientId: 'patient-1',
    patientName: 'Abebe Bekele',
    patientMrn: 'PC-2026-0001',
    branchId: 'branch-main',
    items: [
      { id: 'item-1', description: 'General OPD Specialist Consultation', category: 'consultation', quantity: 1, unitPrice: 400, total: 400 },
      { id: 'item-2', description: 'Paracetamol 500mg (15 tabs)', category: 'pharmacy', quantity: 15, unitPrice: 6.5, total: 97.5 },
    ],
    subtotal: 497.5,
    discount: 0,
    taxPercent: 15,
    taxAmount: 74.62,
    total: 572.12,
    paidAmount: 572.12,
    balanceDue: 0,
    status: 'paid',
    createdAt: '2026-09-25T09:10:00Z',
    dueDate: '2026-09-25',
    payments: [
      {
        id: 'pay-1',
        invoiceId: 'inv-1',
        amount: 572.12,
        method: 'telebirr',
        referenceNumber: 'TB-982184029',
        recordedBy: 'Hanna Gizaw',
        recordedAt: '2026-09-25T09:12:00Z',
        notes: 'Paid in full via Telebirr mobile wallet',
      },
    ],
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2026-0102',
    patientId: 'patient-3',
    patientName: 'Chala Alemu',
    patientMrn: 'PC-2026-0003',
    branchId: 'branch-main',
    items: [
      { id: 'item-3', description: 'Emergency / Urgent Consultation', category: 'consultation', quantity: 1, unitPrice: 600, total: 600 },
      { id: 'item-4', description: 'Complete Blood Count (CBC)', category: 'lab', quantity: 1, unitPrice: 350, total: 350 },
      { id: 'item-5', description: 'Malaria Rapid & Blood Film Exam', category: 'lab', quantity: 1, unitPrice: 220, total: 220 },
      { id: 'item-6', description: 'Amoxicillin 500mg (21 caps)', category: 'pharmacy', quantity: 21, unitPrice: 18.5, total: 388.5 },
      { id: 'item-7', description: 'Paracetamol 500mg (10 tabs)', category: 'pharmacy', quantity: 10, unitPrice: 6.5, total: 65 },
    ],
    subtotal: 1623.5,
    discount: 100, // Courtesy discount
    taxPercent: 15,
    taxAmount: 228.52,
    total: 1752.02,
    paidAmount: 1000.0,
    balanceDue: 752.02,
    status: 'partial',
    createdAt: '2026-09-25T09:30:00Z',
    dueDate: '2026-10-02',
    payments: [
      {
        id: 'pay-2',
        invoiceId: 'inv-2',
        amount: 1000.0,
        method: 'cash',
        referenceNumber: 'RCP-2026-081',
        recordedBy: 'Tariku Fikru',
        recordedAt: '2026-09-25T09:35:00Z',
        notes: 'Partial advance cash payment collected at cashier desk',
      },
    ],
  },
  {
    id: 'inv-3',
    invoiceNumber: 'INV-2026-0103',
    patientId: 'patient-5',
    patientName: 'Eskinder Girma',
    patientMrn: 'PC-2026-0005',
    branchId: 'branch-main',
    items: [
      { id: 'item-8', description: 'Internal Medicine Consultation', category: 'consultation', quantity: 1, unitPrice: 500, total: 500 },
      { id: 'item-9', description: 'Comprehensive Metabolic Panel (CMP)', category: 'lab', quantity: 1, unitPrice: 680, total: 680 },
      { id: 'item-10', description: 'Glycated Hemoglobin (HbA1c)', category: 'lab', quantity: 1, unitPrice: 480, total: 480 },
      { id: 'item-11', description: 'Metformin 850mg (60 tabs)', category: 'pharmacy', quantity: 60, unitPrice: 14.0, total: 840 },
      { id: 'item-12', description: 'Atorvastatin 20mg (30 tabs)', category: 'pharmacy', quantity: 30, unitPrice: 38.0, total: 1140 },
    ],
    subtotal: 3640,
    discount: 0,
    taxPercent: 15,
    taxAmount: 546,
    total: 4186,
    paidAmount: 4186,
    balanceDue: 0,
    status: 'paid',
    createdAt: '2026-09-24T16:30:00Z',
    dueDate: '2026-09-24',
    payments: [
      {
        id: 'pay-3',
        invoiceId: 'inv-3',
        amount: 4186,
        method: 'insurance',
        referenceNumber: 'INS-NYA-89410',
        recordedBy: 'Hanna Gizaw',
        recordedAt: '2026-09-24T16:45:00Z',
        notes: 'Covered 100% by Nyala Corporate Health Policy',
      },
    ],
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-rec-1',
    userName: 'Senait Kebede',
    userRole: 'receptionist',
    action: 'REGISTER_PATIENT',
    module: 'Patients',
    details: 'New patient registered: Chala Alemu (MRN: PC-2026-0003)',
    ipAddress: '192.168.1.42',
    timestamp: '2026-09-25T08:10:00Z',
    branchId: 'branch-main',
  },
  {
    id: 'log-2',
    userId: 'user-nurse-1',
    userName: 'Sister Selamawit Desta',
    userRole: 'nurse',
    action: 'RECORD_VITALS',
    module: 'Clinical',
    details: 'Triage vitals recorded for patient PC-2026-0003. BP: 118/76, Temp: 38.6°C',
    ipAddress: '192.168.1.48',
    timestamp: '2026-09-25T08:15:00Z',
    branchId: 'branch-main',
  },
  {
    id: 'log-3',
    userId: 'user-doc-3',
    userName: 'Dr. Elias Tsegaye',
    userRole: 'doctor',
    action: 'ORDER_LAB_TEST',
    module: 'Laboratory',
    details: 'Ordered CBC and Malaria rapid test for patient PC-2026-0003 (Order LAB-2026-0101)',
    ipAddress: '192.168.1.52',
    timestamp: '2026-09-25T08:45:00Z',
    branchId: 'branch-main',
  },
  {
    id: 'log-4',
    userId: 'user-pharm-1',
    userName: 'PharmD Fitsum Tefera',
    userRole: 'pharmacist',
    action: 'DISPENSE_MEDICATION',
    module: 'Pharmacy',
    details: 'Dispensed 15 tablets of Paracetamol 500mg to patient PC-2026-0001 (Rx-1)',
    ipAddress: '192.168.1.60',
    timestamp: '2026-09-25T09:05:00Z',
    branchId: 'branch-main',
  },
  {
    id: 'log-5',
    userId: 'user-acc-1',
    userName: 'Hanna Gizaw',
    userRole: 'accountant',
    action: 'RECORD_PAYMENT',
    module: 'Billing',
    details: 'Received ETB 572.12 payment via Telebirr for Invoice INV-2026-0101',
    ipAddress: '192.168.1.66',
    timestamp: '2026-09-25T09:12:00Z',
    branchId: 'branch-main',
  },
];

export const initialNotifications: Notification[] = [
  {
    id: 'notif-1',
    roleTarget: 'doctor',
    branchId: 'branch-main',
    title: 'Urgent Lab Result Ready',
    message: 'Malaria Blood Film for Chala Alemu (PC-2026-0003) is POSITIVE for P. Falciparum.',
    type: 'urgent',
    read: false,
    createdAt: '2026-09-25T09:22:00Z',
  },
  {
    id: 'notif-2',
    roleTarget: 'pharmacist',
    branchId: 'branch-main',
    title: 'Critical Stock Alert',
    message: 'Salbutamol Inhaler stock dropped to 18 units (Minimum threshold is 50).',
    type: 'warning',
    read: false,
    createdAt: '2026-09-25T08:00:00Z',
  },
  {
    id: 'notif-3',
    roleTarget: 'nurse',
    branchId: 'branch-main',
    title: 'New Patient in Triage Queue',
    message: 'Derartu Kebede (PC-2026-0004) flagged with emergency chest symptoms.',
    type: 'urgent',
    read: false,
    createdAt: '2026-09-25T09:16:00Z',
  },
  {
    id: 'notif-4',
    roleTarget: 'all',
    branchId: 'branch-main',
    title: 'Branch Scheduled Maintenance',
    message: 'Routine backup and LIS calibration scheduled for Saturday 22:00.',
    type: 'info',
    read: true,
    createdAt: '2026-09-24T18:00:00Z',
  },
];

export const initialSettings: SystemSettings = {
  hospitalName: 'PulseCare Central Hospital & Medical System',
  tagline: 'Enterprise Healthcare Operating Platform',
  email: 'administrator@pulsecare.et',
  phone: '+251 11 661 2000',
  website: 'https://pulsecare.et',
  address: 'Bole Medhanealem Avenue, P.O. Box 1024, Addis Ababa, Ethiopia',
  currency: 'ETB',
  defaultVatRate: 15,
  allowNegativeStock: false,
  requireLabVerification: true,
  language: 'en',
};
